Repository USEPA/CompTox-ToxCast-tcpl, pull requests merged in 2023-11, with the labels that each got.

#143 5 add padilla phase iii sc2 mthds and fix spid character string call
  R/sc2.R
  R/sc2_mthds.R
Labels: bug, enhancement

#167 165 update the model types in ow mc5 methods for plotting
  R/mc5_mthds.R
Labels: enhancement

#171 165 fix for = error on build
  R/mc5_mthds.R
Labels: bug
