Repository USEPA/CompTox-ToxCast-tcpl, pull requests merged in 2023-08, with the labels that each got.

#115 106 Created mc4 bmad5.onesd16.static method
  R/mc4_mthds.R
Labels: enhancement

#130 125 mc2 aggpercentrepspidmin1
  R/mc2_mthds.R
Labels: enhancement, documentation

#123 85 add bidirectional mc5 methods
  R/mc4.R
  R/mc5.R
  R/mc5_mthds.R
  R/mc6_mthds.R
  R/tcplFit2.R
  R/tcplLoadData.R
  R/v3_schema_functions.R
Labels: enhancement

#126 62 bidirectional summary stats
  R/mc4.R
  R/mc5.R
  R/mc6_mthds.R
  R/tcplFit2.R
  R/tcplLoadData.R
  R/v3_schema_functions.R
Labels: enhancement, invalid
