Repository USEPA/CompTox-ToxCast-tcpl, pull requests merged in 2024-04, with the labels that each got.

#201 Add ToxRefDB-AED comparison section to data retrieval vignette
  vignettes/Data_retrieval.Rmd
  vignettes/img/ccd_seqapass_filter.png
Labels: enhancement

#221 202 integrate ccdR into tcpl load data
  DESCRIPTION
  NAMESPACE
  R/data.R
  R/query_funcs.R
  R/tcplConf.R
  R/tcplLoadAeid.R
  R/tcplLoadData.R
  R/tcplQueryAPI.R
  data-raw/tcplLoadData_columns.R
  data/load_data_columns.rda
  man/load_data_columns.Rd
  man/query_funcs.Rd
  man/tcplLoadData.Rd
Labels: enhancement

#225 216 backwards compatibility checks fixes
  R/tcplMakeAeidMultiPlts.R
  R/tcplMakeAeidPlts.R
  R/tcplMakeChidMultiPlts.R
  R/tcplMultiplot.R
  R/tcplPlot.R
  R/tcplPlotFitc.R
  R/tcplPlotFits.R
  R/tcplPlotM4ID.R
  R/tcplPlotPlate.R
  R/tcplSubsetChid.R
Labels: bug

#222 220 update mc6 methods to use model_type, update descs, remove no.med.single.dir.gt.3bmad
  R/mc6_mthds.R
Labels: bug

#229 226/172 tcpl plot fails when winning model is none/unregistered chemicals do not show NA
  R/tcplPlot.R
Labels: bug, enhancement

#186 161/82 investigate combined sc-mc output: tcplVarMat() overhaul
  NAMESPACE
  R/tcplLoadData.R
  R/tcplSubsetChid.R
  R/tcplVarMat.R
  man/tcplVarMat.Rd
Labels: bug, enhancement
